# Sevalla deployment configuration
version: 2

build:
  os: ubuntu-20.04

  install:
    - echo "Installing dependencies..."
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
    - sudo apt-get install -y nodejs

  commands:
    - echo "Installing Composer dependencies..."
    - composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader --no-scripts
    - echo "Installing Node.js dependencies..."
    - npm ci
    - echo "Building frontend assets..."
    - npm run build
    - echo "Running Laravel optimizations..."
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache

web:
  locations:
    /:
      root: /public
      index: index.php

    ~ \.php$:
      fastcgi_pass: php:9000
      fastcgi_index: index.php
      fastcgi_param: SCRIPT_FILENAME $document_root$fastcgi_script_name
      include: fastcgi_params

runtime:
  php:
    version: "8.2"
    extensions:
      - pdo_mysql
      - mbstring
      - xml
      - ctype
      - json
      - tokenizer
      - openssl
      - pcntl
      - bcmath
      - gd
      - zip

environment:
  APP_ENV: production
  APP_DEBUG: false
